# Generated by Django 2.0.3 on 2018-03-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=4096)),
                ('img_url', models.CharField(max_length=256, unique=True)),
                ('hashtags', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('photo_url', models.CharField(max_length=256)),
                ('post_num', models.IntegerField()),
                ('follower_num', models.IntegerField()),
                ('following_num', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.SocialUser'),
        ),
    ]
