# Generated by Django 2.0.3 on 2018-03-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes_num',
            field=models.IntegerField(default=0),
        ),
    ]
