# Generated by Django 2.0.3 on 2018-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20180312_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialuser',
            name='engagement',
            field=models.FloatField(default=0.0),
        ),
    ]
